"""add_tenants_table

Revision ID: 6fb21bf9ba7e
Revises: b7f203196991
Create Date: 2026-09-01 22:27:18.875000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlmodel import SQLModel

# revision identifiers, used by Alembic.
revision: str = "6fb21bf9ba7e"
down_revision: Union[str, Sequence[str], None] = "b7f203196991"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "tenant_name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "suspended", "archived", name="tenantstatus"),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "slug", name="uq_tenant_slug_per_org"),
    )
    op.create_index(
        op.f("ix_tenants_organization_id"), "tenants", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=False)
    op.create_index(op.f("ix_tenants_status"), "tenants", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tenants_status"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_organization_id"), table_name="tenants")
    op.drop_table("tenants")
    # ### end Alembic commands ###
